spring.application.name=note-service
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.profiles.active=local

spring.cloud.gateway.default-filters[0]=PreserveHostHeader

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB