server.port = 8080

spring.data.mongodb.uri= ${MONGODB_URI}



# this is 64 string here im using the HS256/HS512 encryption 
jwt.secret=${JWT_SECRET}


# if key is very short it will throw the weakkeyexception

jwt.expiration.ms=86400000    

spring.data.mongodb.connection-pool.max-size=20
spring.data.mongodb.connection-pool.min-size=5
spring.data.mongodb.connection-pool.max-wait-time.ms=2000

server.http2.enabled=true

deepseek.api.key = ${DEEPSEEK_API_KEY}
deepseek.api.url = https://api.deepseek.com/v1/chat/completions
deepseek.model = deepseek-v4-flash

spring.profiles.active=local